shim-version: v0.2.10@sha256:f9040a48106ab06c290fd9b225d4dd53a2daad715c9107594d4310b21592039f
cvm-version: 0.5.6
cpus: 4
memory: 4096
gpus: none
vllm: false

containers:
  - name: "titan-qwen-0.5b-gguf"
    image: "ghcr.io/tinfoilsh/titan-qwen-0.5b-gguf:v0.0.1"
    args: [
      "-e", "MODEL_NAME=theprint/TiTan-Qwen2.5-0.5B-GGUF",
      "-e", "PORT=8000",
      "-e", "CONTEXT_SIZE=8192",
      "-e", "CUDA_VISIBLE_DEVICES="
    ]

shim:
  listen-port: 443
  upstream-port: 8000
  publish-attestation: false
  tls-challenge: dns  
  control-plane: https://api.tinfoil.sh
  paths:
    - /v1/chat/completions
    - /health
    - /v1/models
    - /metrics
