shim-version: v0.2.11@sha256:cbbbeeac855948610cd1ba5b406d10ffa13331cbbe7d25964ba3c90486f65810
cvm-version: 0.5.6
cpus: 4
memory: 4096
gpus: none
vllm: false

containers:
  - name: "titan-qwen-0.5b-gguf"
    image: "ghcr.io/tinfoilsh/titan-qwen-0.5b-gguf:v0.0.4"
    args: [
      "-e", "MODEL_NAME=theprint/TiTan-Qwen2.5-0.5B-GGUF",
      "-e", "SERVED_MODEL_NAME=titan-qwen2-5-05b",
      "-e", "PORT=8000",
      "-e", "CONTEXT_SIZE=8192",
      "-e", "CUDA_VISIBLE_DEVICES="
    ]

shim:
  listen-port: 443
  upstream-port: 8000
  publish-attestation: false
  tls-challenge: dns  
  paths:
    - /v1/chat/completions
    - /health
    - /v1/models
    - /metrics
